
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Apr 20 2022 13:57:46 +07 (Apr 20 2022 06:57:46 UTC)

// Verification Directory fv/boundFlasher 

module boundFlasher(flick, clk, rst, LEDs);
  input flick, clk, rst;
  output [15:0] LEDs;
  wire flick, clk, rst;
  wire [15:0] LEDs;
  wire [2:0] stateTemp;
  wire [2:0] stateReal;
  wire [15:0] ledTemp;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_11, n_12, n_14;
  wire n_15, n_16, n_17, n_25, n_26, n_29, n_30, n_31;
  wire n_32, n_33, n_37, n_38, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_66, n_69, n_72, n_74, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_95, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_111, n_117;
  TLATX1 \stateTemp_reg[1] (.G (n_62), .D (n_60), .Q (stateTemp[1]),
       .QN (UNCONNECTED));
  TLATX1 \stateTemp_reg[2] (.G (n_62), .D (n_61), .Q (stateTemp[2]),
       .QN (UNCONNECTED0));
  TLATX1 \stateTemp_reg[0] (.G (n_62), .D (n_54), .Q (stateTemp[0]),
       .QN (UNCONNECTED1));
  OAI211X1 g2626__2398(.A0 (stateReal[1]), .A1 (n_30), .B0 (rst), .C0
       (n_55), .Y (n_62));
  OAI32X1 g2627__5107(.A0 (n_59), .A1 (n_58), .A2 (n_56), .B0 (n_57),
       .B1 (n_47), .Y (n_61));
  OAI33X1 g2628__6260(.A0 (n_46), .A1 (n_15), .A2 (n_51), .B0 (n_59),
       .B1 (n_58), .B2 (n_50), .Y (n_60));
  NOR3XL g2631__4319(.A (stateTemp[2]), .B (n_53), .C (n_56), .Y
       (n_57));
  AOI22XL g2629__8428(.A0 (stateReal[1]), .A1 (n_52), .B0
       (stateReal[0]), .B1 (n_43), .Y (n_55));
  OAI32X1 g2630__5526(.A0 (n_53), .A1 (n_25), .A2 (n_49), .B0
       (stateReal[0]), .B1 (n_16), .Y (n_54));
  MXI2XL g2632__6783(.A (n_69), .B (n_45), .S0 (stateReal[0]), .Y
       (n_52));
  OA21X1 g2633__3680(.A0 (n_48), .A1 (n_12), .B0 (stateReal[2]), .Y
       (n_51));
  INVXL g2638(.A (n_50), .Y (n_56));
  OR2X1 g2639__1617(.A (n_48), .B (n_47), .Y (n_49));
  DFFRHQX4 \LEDs_reg[10] (.RN (rst), .CK (clk), .D (ledTemp[10]), .Q
       (LEDs[10]));
  NOR2XL g2642__2802(.A (n_46), .B (n_48), .Y (n_50));
  DFFRHQX4 \LEDs_reg[12] (.RN (rst), .CK (clk), .D (ledTemp[12]), .Q
       (LEDs[12]));
  DFFRHQX4 \LEDs_reg[5] (.RN (rst), .CK (clk), .D (ledTemp[5]), .Q
       (LEDs[5]));
  DFFRHQX4 \LEDs_reg[2] (.RN (rst), .CK (clk), .D (ledTemp[2]), .Q
       (LEDs[2]));
  DFFRHQX4 \LEDs_reg[7] (.RN (rst), .CK (clk), .D (ledTemp[7]), .Q
       (LEDs[7]));
  DFFRHQX4 \LEDs_reg[0] (.RN (rst), .CK (clk), .D (ledTemp[0]), .Q
       (LEDs[0]));
  TLATX1 \ledTemp_reg[12] (.G (n_44), .D (n_78), .Q (ledTemp[12]), .QN
       (UNCONNECTED2));
  OAI31X1 g2640__1705(.A0 (n_31), .A1 (stateTemp[0]), .A2 (n_2), .B0
       (n_32), .Y (n_45));
  TLATX1 \ledTemp_reg[10] (.G (n_44), .D (n_84), .Q (ledTemp[10]), .QN
       (UNCONNECTED3));
  OA21X1 g2651__5122(.A0 (n_33), .A1 (n_42), .B0 (flick), .Y (n_48));
  TLATX1 \ledTemp_reg[0] (.G (n_44), .D (n_117), .Q (ledTemp[0]), .QN
       (UNCONNECTED4));
  TLATX1 \ledTemp_reg[2] (.G (n_44), .D (n_102), .Q (ledTemp[2]), .QN
       (UNCONNECTED5));
  TLATX1 \ledTemp_reg[7] (.G (n_44), .D (n_87), .Q (ledTemp[7]), .QN
       (UNCONNECTED6));
  TLATX1 \ledTemp_reg[5] (.G (n_44), .D (n_93), .Q (ledTemp[5]), .QN
       (UNCONNECTED7));
  OAI2BB1X1 g2650__8246(.A0N (flick), .A1N (n_42), .B0 (n_14), .Y
       (n_43));
  NOR2BX1 g2658__4733(.AN (n_29), .B (n_72), .Y (n_42));
  NOR2BX1 g2659__6161(.AN (n_32), .B (n_66), .Y (n_33));
  NOR2BX1 g2660__9315(.AN (flick), .B (n_66), .Y (n_31));
  DFFRHQX4 \LEDs_reg[1] (.RN (rst), .CK (clk), .D (ledTemp[1]), .Q
       (LEDs[1]));
  DFFRHQX4 \LEDs_reg[3] (.RN (rst), .CK (clk), .D (ledTemp[3]), .Q
       (LEDs[3]));
  DFFRHQX4 \LEDs_reg[13] (.RN (rst), .CK (clk), .D (ledTemp[13]), .Q
       (LEDs[13]));
  DFFRHQX4 \LEDs_reg[6] (.RN (rst), .CK (clk), .D (ledTemp[6]), .Q
       (LEDs[6]));
  DFFRHQX4 \LEDs_reg[11] (.RN (rst), .CK (clk), .D (ledTemp[11]), .Q
       (LEDs[11]));
  DFFRHQX4 \LEDs_reg[15] (.RN (rst), .CK (clk), .D (ledTemp[15]), .Q
       (LEDs[15]));
  DFFRHQX4 \LEDs_reg[4] (.RN (rst), .CK (clk), .D (ledTemp[4]), .Q
       (LEDs[4]));
  DFFRHQX4 \LEDs_reg[9] (.RN (rst), .CK (clk), .D (ledTemp[9]), .Q
       (LEDs[9]));
  DFFRHQX4 \LEDs_reg[14] (.RN (rst), .CK (clk), .D (ledTemp[14]), .Q
       (LEDs[14]));
  DFFRHQX4 \LEDs_reg[8] (.RN (rst), .CK (clk), .D (ledTemp[8]), .Q
       (LEDs[8]));
  TLATX1 \ledTemp_reg[1] (.G (n_44), .D (n_100), .Q (ledTemp[1]), .QN
       (UNCONNECTED8));
  TLATX1 \ledTemp_reg[14] (.G (n_44), .D (n_79), .Q (ledTemp[14]), .QN
       (UNCONNECTED9));
  TLATX1 \ledTemp_reg[3] (.G (n_44), .D (n_99), .Q (ledTemp[3]), .QN
       (UNCONNECTED10));
  TLATX1 \ledTemp_reg[9] (.G (n_44), .D (n_88), .Q (ledTemp[9]), .QN
       (UNCONNECTED11));
  TLATX1 \ledTemp_reg[8] (.G (n_44), .D (n_90), .Q (ledTemp[8]), .QN
       (UNCONNECTED12));
  TLATX1 \ledTemp_reg[13] (.G (n_44), .D (n_81), .Q (ledTemp[13]), .QN
       (UNCONNECTED13));
  TLATX1 \ledTemp_reg[11] (.G (n_44), .D (n_82), .Q (ledTemp[11]), .QN
       (UNCONNECTED14));
  TLATX1 \ledTemp_reg[6] (.G (n_44), .D (n_91), .Q (ledTemp[6]), .QN
       (UNCONNECTED15));
  TLATX1 \ledTemp_reg[4] (.G (n_44), .D (n_97), .Q (ledTemp[4]), .QN
       (UNCONNECTED16));
  TLATX1 \ledTemp_reg[15] (.G (n_44), .D (n_76), .Q (ledTemp[15]), .QN
       (UNCONNECTED17));
  NAND2X1 g2681__9945(.A (n_17), .B (n_26), .Y (n_44));
  AOI222X1 g2682__2883(.A0 (n_46), .A1 (n_11), .B0 (stateReal[2]), .B1
       (n_5), .C0 (n_29), .C1 (stateReal[0]), .Y (n_30));
  AOI32X1 g2683__7410(.A0 (n_29), .A1 (n_7), .A2 (n_25), .B0
       (stateTemp[0]), .B1 (n_9), .Y (n_26));
  AOI22XL g2693__5526(.A0 (n_8), .A1 (n_6), .B0 (n_69), .B1 (n_0), .Y
       (n_17));
  AND2X1 g2696__6783(.A (n_58), .B (n_15), .Y (n_16));
  OR2X1 g2695__3680(.A (n_14), .B (n_15), .Y (n_47));
  AOI21XL g2697__2802(.A0 (n_53), .A1 (n_3), .B0 (stateTemp[1]), .Y
       (n_12));
  AND2X1 g2700__1705(.A (flick), .B (n_14), .Y (n_11));
  OAI221X1 g2698__5122(.A0 (n_53), .A1 (n_8), .B0 (n_32), .B1 (n_7),
       .C0 (n_1), .Y (n_9));
  NAND2XL g2701__8246(.A (n_59), .B (rst), .Y (n_15));
  AO22X1 g2704__7098(.A0 (n_5), .A1 (n_7), .B0 (n_69), .B1 (n_25), .Y
       (n_6));
  NAND2XL g2703__6131(.A (n_3), .B (n_2), .Y (n_4));
  NAND2XL g2705__1881(.A (n_14), .B (rst), .Y (n_58));
  OAI2BB1X1 g2706__5115(.A0N (n_25), .A1N (stateTemp[1]), .B0 (n_3), .Y
       (n_38));
  AND2X1 g2702__7482(.A (stateTemp[0]), .B (n_1), .Y (n_37));
  INVXL g2713(.A (n_1), .Y (n_0));
  NAND2XL g2714__4733(.A (stateTemp[1]), .B (n_8), .Y (n_2));
  NAND2XL g2715__6161(.A (stateTemp[2]), .B (n_25), .Y (n_3));
  NAND2XL g2716__9315(.A (stateTemp[2]), .B (stateTemp[1]), .Y (n_1));
  INVXL g2721(.A (n_29), .Y (n_5));
  INVXL g2720(.A (stateTemp[1]), .Y (n_7));
  INVXL g2723(.A (stateTemp[0]), .Y (n_25));
  BUFX2 g2722(.A (LEDs[5]), .Y (n_29));
  INVXL g2717(.A (stateTemp[2]), .Y (n_8));
  BUFX2 g2718(.A (LEDs[10]), .Y (n_32));
  BUFX2 g2719(.A (LEDs[15]), .Y (n_53));
  BUFX2 fopt2765(.A (LEDs[0]), .Y (n_69));
  BUFX2 fopt2767(.A (LEDs[6]), .Y (n_72));
  BUFX2 fopt2769(.A (LEDs[11]), .Y (n_66));
  BUFX2 g1(.A (LEDs[14]), .Y (n_74));
  AND2X1 g2694__2773(.A (n_74), .B (n_37), .Y (n_76));
  AO22X1 g2657__2774(.A0 (n_66), .A1 (n_111), .B0 (n_77), .B1 (n_38),
       .Y (n_78));
  BUFX2 g2775(.A (LEDs[13]), .Y (n_77));
  AO22X1 g2692__2776(.A0 (n_53), .A1 (n_38), .B0 (n_77), .B1 (n_37), .Y
       (n_79));
  AO22X1 g2689__2777(.A0 (n_74), .A1 (n_38), .B0 (n_80), .B1 (n_111),
       .Y (n_81));
  BUFX2 g2778(.A (LEDs[12]), .Y (n_80));
  AO22X1 g2690__2779(.A0 (n_80), .A1 (n_38), .B0 (n_32), .B1 (n_37), .Y
       (n_82));
  AO22X1 g2656__2780(.A0 (n_66), .A1 (n_38), .B0 (n_83), .B1 (n_111),
       .Y (n_84));
  BUFX2 g2781(.A (LEDs[9]), .Y (n_83));
  AO22X1 g2655__2783(.A0 (n_72), .A1 (n_37), .B0 (n_86), .B1 (n_38), .Y
       (n_87));
  BUFX2 g2784(.A (LEDs[8]), .Y (n_86));
  AO22X1 g2691__2785(.A0 (n_32), .A1 (n_38), .B0 (n_86), .B1 (n_111),
       .Y (n_88));
  AO22X1 g2688__2786(.A0 (n_83), .A1 (n_38), .B0 (n_89), .B1 (n_37), .Y
       (n_90));
  BUFX2 g2787(.A (LEDs[7]), .Y (n_89));
  AO22X1 g2687__2788(.A0 (n_89), .A1 (n_38), .B0 (n_29), .B1 (n_111),
       .Y (n_91));
  AO22X1 g2654__2789(.A0 (n_72), .A1 (n_38), .B0 (n_92), .B1 (n_37), .Y
       (n_93));
  BUFX2 g2790(.A (LEDs[4]), .Y (n_92));
  BUFX2 g2793(.A (LEDs[3]), .Y (n_95));
  AO22X1 g2685__2794(.A0 (n_29), .A1 (n_38), .B0 (n_95), .B1 (n_111),
       .Y (n_97));
  AO22X1 g2684__2795(.A0 (n_92), .A1 (n_38), .B0 (n_98), .B1 (n_37), .Y
       (n_99));
  BUFX2 g2796(.A (LEDs[2]), .Y (n_98));
  AO22X1 g2686__2797(.A0 (n_98), .A1 (n_38), .B0 (n_69), .B1 (n_111),
       .Y (n_100));
  AO22X1 g2653__2798(.A0 (n_101), .A1 (n_111), .B0 (n_95), .B1 (n_38),
       .Y (n_102));
  BUFX2 g2799(.A (LEDs[1]), .Y (n_101));
  BUFX2 drc_buf_sp2807(.A (n_37), .Y (n_111));
  DFFRX1 \stateReal_reg[1] (.RN (rst), .CK (clk), .D (stateTemp[1]), .Q
       (stateReal[1]), .QN (n_59));
  DFFRX1 \stateReal_reg[0] (.RN (rst), .CK (clk), .D (stateTemp[0]), .Q
       (stateReal[0]), .QN (n_46));
  DFFRX1 \stateReal_reg[2] (.RN (rst), .CK (clk), .D (stateTemp[2]), .Q
       (stateReal[2]), .QN (n_14));
  AO21X1 g2(.A0 (n_101), .A1 (n_4), .B0 (n_37), .Y (n_117));
endmodule

